; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mcpu=veyron-v2 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define <8 x i32> @generate_vwadaccu_8i8_zeroinit(<8 x i8> %v0, <8 x i8> %v1)  {
; CHECK-LABEL: generate_vwadaccu_8i8_zeroinit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v10, 0
; CHECK-NEXT:    vsetvli zero, zero, e8, mf8, ta, ma
; CHECK-NEXT:    vwadaccu.vv v10, v8, v9
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %zext0_ = zext <8 x i8> %v0 to <8 x i16>
  %zext1_ = zext <8 x i8> %v1 to <8 x i16>
  %sub_ = sub nsw <8 x i16> %zext0_, %zext1_
  %abs_ = tail call <8 x i16> @llvm.abs.v8i16(<8 x i16> %sub_, i1 false)
  %res = zext <8 x i16> %abs_ to <8 x i32>
  ret <8 x i32> %res
}

define <16 x i32> @generate_vwadaccu_16i8_zeroinit(<16 x i8> %v0, <16 x i8> %v1)  {
; CHECK-LABEL: generate_vwadaccu_16i8_zeroinit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v10, 0
; CHECK-NEXT:    vsetvli zero, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vwadaccu.vv v10, v8, v9
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %zext0_ = zext <16 x i8> %v0 to <16 x i16>
  %zext1_ = zext <16 x i8> %v1 to <16 x i16>
  %sub_ = sub nsw <16 x i16> %zext0_, %zext1_
  %abs_ = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> %sub_, i1 false)
  %res = zext <16 x i16> %abs_ to <16 x i32>
  ret <16 x i32> %res
}

define <16 x i32> @generate_vwadaccu_16i8_nonzeroinit(<16 x i8> %v0, <16 x i8> %v1, <16 x i32> %acc)  {
; CHECK-LABEL: generate_vwadaccu_16i8_nonzeroinit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, mf4, ta, ma
; CHECK-NEXT:    vwadaccu.vv v10, v8, v9
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %zext0_ = zext <16 x i8> %v0 to <16 x i16>
  %zext1_ = zext <16 x i8> %v1 to <16 x i16>
  %sub_ = sub nsw <16 x i16> %zext0_, %zext1_
  %abs_ = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> %sub_, i1 false)
  %zexti32 = zext <16 x i16> %abs_ to <16 x i32>
  %res = add <16 x i32> %zexti32, %acc
  ret <16 x i32> %res
}
