; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=predicated -mattr=+v -S < %s | FileCheck %s
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=masked -mattr=+v -S < %s | FileCheck %s --check-prefix=MASKED

define i1 @check_equality_byte(ptr noundef readonly %theLHS, i64 noundef %theLHSLength, ptr nocapture noundef readonly %theRHS, i64 noundef %theRHSLength) {
; CHECK-LABEL: define i1 @check_equality_byte(
; CHECK-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; CHECK:       [[IF_ELSE3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[THELHS]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[THERHS]], align 1
; CHECK-NEXT:    [[CMP518:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP518]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_COND:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP4:%.*]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[INDEX:%.*]], [[TMP2]]
; CHECK-NEXT:    [[DOTNOT2:%.*]] = icmp eq i64 [[TMP3]], [[THELHSLENGTH]]
; CHECK-NEXT:    br i1 [[DOTNOT2]], label %[[RETURN_LOOPEXIT:.*]], label %[[WHILE_BODY]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX]] = phi i64 [ 0, %[[WHILE_BODY_PREHEADER]] ], [ [[TMP3]], %[[WHILE_COND]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub nuw nsw i64 [[THELHSLENGTH]], [[INDEX]]
; CHECK-NEXT:    [[TMP4]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[THELHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr [[TMP5]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr [[TMP7]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP6]], <vscale x 16 x i8> [[TMP8]], metadata !"ne", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP9]], i1 false, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[TMP10]], [[TMP4]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label %[[WHILE_COND]], label %[[RETURN_LOOPEXIT]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[DOTNOT]], %[[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[RETVAL_1]]
;
; MASKED-LABEL: define i1 @check_equality_byte(
; MASKED-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0:[0-9]+]] {
; MASKED-NEXT:  [[ENTRY:.*]]:
; MASKED-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; MASKED-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; MASKED:       [[IF_ELSE]]:
; MASKED-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; MASKED-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; MASKED:       [[IF_ELSE3]]:
; MASKED-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[THELHS]], i64 [[THELHSLENGTH]]
; MASKED-NEXT:    [[TMP0:%.*]] = load i8, ptr [[THELHS]], align 1
; MASKED-NEXT:    [[TMP1:%.*]] = load i8, ptr [[THERHS]], align 1
; MASKED-NEXT:    [[CMP518:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; MASKED-NEXT:    br i1 [[CMP518]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[WHILE_COND:.*]]:
; MASKED-NEXT:    [[INCDEC_PTR11:%.*]] = getelementptr inbounds nuw i8, ptr [[THERHS_ADDR_019:%.*]], i64 1
; MASKED-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR:%.*]], align 1
; MASKED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[INCDEC_PTR11]], align 1
; MASKED-NEXT:    [[CMP5:%.*]] = icmp eq i8 [[TMP2]], [[TMP3]]
; MASKED-NEXT:    br i1 [[CMP5]], label %[[WHILE_BODY]], label %[[RETURN_LOOPEXIT:.*]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[THELHS_ADDR_020:%.*]] = phi ptr [ [[INCDEC_PTR]], %[[WHILE_COND]] ], [ [[THELHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[THERHS_ADDR_019]] = phi ptr [ [[INCDEC_PTR11]], %[[WHILE_COND]] ], [ [[THERHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[THELHS_ADDR_020]], i64 1
; MASKED-NEXT:    [[CMP7:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[ADD_PTR]]
; MASKED-NEXT:    br i1 [[CMP7]], label %[[RETURN_LOOPEXIT]], label %[[WHILE_COND]]
; MASKED:       [[RETURN_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[RETURN]]
; MASKED:       [[RETURN]]:
; MASKED-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[CMP7]], %[[RETURN_LOOPEXIT]] ]
; MASKED-NEXT:    ret i1 [[RETVAL_1]]
;
entry:
  %cmp.not = icmp eq i64 %theLHSLength, %theRHSLength
  br i1 %cmp.not, label %if.else, label %return

if.else:
  %cmp1 = icmp eq i64 %theLHSLength, 0
  br i1 %cmp1, label %return, label %if.else3

if.else3:
  %add.ptr = getelementptr inbounds nuw i8, ptr %theLHS, i64 %theLHSLength
  %0 = load i8, ptr %theLHS, align 1
  %1 = load i8, ptr %theRHS, align 1
  %cmp518 = icmp eq i8 %0, %1
  br i1 %cmp518, label %while.body, label %return

while.cond:
  %incdec.ptr11 = getelementptr inbounds nuw i8, ptr %theRHS.addr.019, i64 1
  %2 = load i8, ptr %incdec.ptr, align 1
  %3 = load i8, ptr %incdec.ptr11, align 1
  %cmp5 = icmp eq i8 %2, %3
  br i1 %cmp5, label %while.body, label %return

while.body:
  %theLHS.addr.020 = phi ptr [ %incdec.ptr, %while.cond ], [ %theLHS, %if.else3 ]
  %theRHS.addr.019 = phi ptr [ %incdec.ptr11, %while.cond ], [ %theRHS, %if.else3 ]
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %theLHS.addr.020, i64 1
  %cmp7 = icmp eq ptr %incdec.ptr, %add.ptr
  br i1 %cmp7, label %return, label %while.cond

return:
  %retval.1 = phi i1 [ false, %entry ], [ true, %if.else ], [ false, %if.else3 ], [ %cmp7, %while.body ], [ %cmp7, %while.cond ]
  ret i1 %retval.1
}

define i1 @check_equality_short(ptr noundef readonly %theLHS, i64 noundef %theLHSLength, ptr nocapture noundef readonly %theRHS, i64 noundef %theRHSLength) {
; CHECK-LABEL: define i1 @check_equality_short(
; CHECK-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; CHECK:       [[IF_ELSE3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[THELHS]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[THERHS]], align 2
; CHECK-NEXT:    [[CMP518:%.*]] = icmp eq i16 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP518]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_COND:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP4:%.*]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[INDEX:%.*]], [[TMP2]]
; CHECK-NEXT:    [[DOTNOT2:%.*]] = icmp eq i64 [[TMP3]], [[THELHSLENGTH]]
; CHECK-NEXT:    br i1 [[DOTNOT2]], label %[[RETURN_LOOPEXIT:.*]], label %[[WHILE_BODY]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX]] = phi i64 [ 0, %[[WHILE_BODY_PREHEADER]] ], [ [[TMP3]], %[[WHILE_COND]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub nuw nsw i64 [[THELHSLENGTH]], [[INDEX]]
; CHECK-NEXT:    [[TMP4]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i16, ptr [[THELHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i16> @llvm.vp.load.nxv16i16.p0(ptr [[TMP5]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i16, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i16> @llvm.vp.load.nxv16i16.p0(ptr [[TMP7]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP6]], <vscale x 16 x i16> [[TMP8]], metadata !"ne", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP9]], i1 false, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[TMP10]], [[TMP4]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label %[[WHILE_COND]], label %[[RETURN_LOOPEXIT]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[DOTNOT]], %[[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[RETVAL_1]]
;
; MASKED-LABEL: define i1 @check_equality_short(
; MASKED-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0]] {
; MASKED-NEXT:  [[ENTRY:.*]]:
; MASKED-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; MASKED-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; MASKED:       [[IF_ELSE]]:
; MASKED-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; MASKED-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; MASKED:       [[IF_ELSE3]]:
; MASKED-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i16, ptr [[THELHS]], i64 [[THELHSLENGTH]]
; MASKED-NEXT:    [[TMP0:%.*]] = load i16, ptr [[THELHS]], align 2
; MASKED-NEXT:    [[TMP1:%.*]] = load i16, ptr [[THERHS]], align 2
; MASKED-NEXT:    [[CMP518:%.*]] = icmp eq i16 [[TMP0]], [[TMP1]]
; MASKED-NEXT:    br i1 [[CMP518]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[WHILE_COND:.*]]:
; MASKED-NEXT:    [[INCDEC_PTR11:%.*]] = getelementptr inbounds nuw i8, ptr [[THERHS_ADDR_019:%.*]], i64 2
; MASKED-NEXT:    [[TMP2:%.*]] = load i16, ptr [[INCDEC_PTR:%.*]], align 2
; MASKED-NEXT:    [[TMP3:%.*]] = load i16, ptr [[INCDEC_PTR11]], align 2
; MASKED-NEXT:    [[CMP5:%.*]] = icmp eq i16 [[TMP2]], [[TMP3]]
; MASKED-NEXT:    br i1 [[CMP5]], label %[[WHILE_BODY]], label %[[RETURN_LOOPEXIT:.*]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[THELHS_ADDR_020:%.*]] = phi ptr [ [[INCDEC_PTR]], %[[WHILE_COND]] ], [ [[THELHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[THERHS_ADDR_019]] = phi ptr [ [[INCDEC_PTR11]], %[[WHILE_COND]] ], [ [[THERHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[THELHS_ADDR_020]], i64 2
; MASKED-NEXT:    [[CMP7:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[ADD_PTR]]
; MASKED-NEXT:    br i1 [[CMP7]], label %[[RETURN_LOOPEXIT]], label %[[WHILE_COND]]
; MASKED:       [[RETURN_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[RETURN]]
; MASKED:       [[RETURN]]:
; MASKED-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[CMP7]], %[[RETURN_LOOPEXIT]] ]
; MASKED-NEXT:    ret i1 [[RETVAL_1]]
;
entry:
  %cmp.not = icmp eq i64 %theLHSLength, %theRHSLength
  br i1 %cmp.not, label %if.else, label %return

if.else:
  %cmp1 = icmp eq i64 %theLHSLength, 0
  br i1 %cmp1, label %return, label %if.else3

if.else3:
  %add.ptr = getelementptr inbounds nuw i16, ptr %theLHS, i64 %theLHSLength
  %0 = load i16, ptr %theLHS, align 2
  %1 = load i16, ptr %theRHS, align 2
  %cmp518 = icmp eq i16 %0, %1
  br i1 %cmp518, label %while.body, label %return

while.cond:
  %incdec.ptr11 = getelementptr inbounds nuw i8, ptr %theRHS.addr.019, i64 2
  %2 = load i16, ptr %incdec.ptr, align 2
  %3 = load i16, ptr %incdec.ptr11, align 2
  %cmp5 = icmp eq i16 %2, %3
  br i1 %cmp5, label %while.body, label %return

while.body:
  %theLHS.addr.020 = phi ptr [ %incdec.ptr, %while.cond ], [ %theLHS, %if.else3 ]
  %theRHS.addr.019 = phi ptr [ %incdec.ptr11, %while.cond ], [ %theRHS, %if.else3 ]
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %theLHS.addr.020, i64 2
  %cmp7 = icmp eq ptr %incdec.ptr, %add.ptr
  br i1 %cmp7, label %return, label %while.cond

return:
  %retval.1 = phi i1 [ false, %entry ], [ true, %if.else ], [ false, %if.else3 ], [ %cmp7, %while.body ], [ %cmp7, %while.cond ]
  ret i1 %retval.1
}

define i1 @check_equality_word(ptr noundef readonly %theLHS, i64 noundef %theLHSLength, ptr nocapture noundef readonly %theRHS, i64 noundef %theRHSLength) {
; CHECK-LABEL: define i1 @check_equality_word(
; CHECK-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; CHECK:       [[IF_ELSE3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[THELHS]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[THERHS]], align 4
; CHECK-NEXT:    [[CMP415:%.*]] = icmp eq i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP415]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_COND:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP4:%.*]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[INDEX:%.*]], [[TMP2]]
; CHECK-NEXT:    [[DOTNOT2:%.*]] = icmp eq i64 [[TMP3]], [[THELHSLENGTH]]
; CHECK-NEXT:    br i1 [[DOTNOT2]], label %[[RETURN_LOOPEXIT:.*]], label %[[WHILE_BODY]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX]] = phi i64 [ 0, %[[WHILE_BODY_PREHEADER]] ], [ [[TMP3]], %[[WHILE_COND]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub nuw nsw i64 [[THELHSLENGTH]], [[INDEX]]
; CHECK-NEXT:    [[TMP4]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[THELHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr [[TMP5]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr [[TMP7]], <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i32(<vscale x 16 x i32> [[TMP6]], <vscale x 16 x i32> [[TMP8]], metadata !"ne", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP9]], i1 false, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[TMP10]], [[TMP4]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label %[[WHILE_COND]], label %[[RETURN_LOOPEXIT]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[DOTNOT]], %[[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[RETVAL_1]]
;
; MASKED-LABEL: define i1 @check_equality_word(
; MASKED-SAME: ptr noundef readonly [[THELHS:%.*]], i64 noundef [[THELHSLENGTH:%.*]], ptr nocapture noundef readonly [[THERHS:%.*]], i64 noundef [[THERHSLENGTH:%.*]]) #[[ATTR0]] {
; MASKED-NEXT:  [[ENTRY:.*]]:
; MASKED-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[THELHSLENGTH]], [[THERHSLENGTH]]
; MASKED-NEXT:    br i1 [[CMP_NOT]], label %[[IF_ELSE:.*]], label %[[RETURN:.*]]
; MASKED:       [[IF_ELSE]]:
; MASKED-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[THELHSLENGTH]], 0
; MASKED-NEXT:    br i1 [[CMP1]], label %[[RETURN]], label %[[IF_ELSE3:.*]]
; MASKED:       [[IF_ELSE3]]:
; MASKED-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i32, ptr [[THELHS]], i64 [[THELHSLENGTH]]
; MASKED-NEXT:    [[TMP0:%.*]] = load i32, ptr [[THELHS]], align 4
; MASKED-NEXT:    [[TMP1:%.*]] = load i32, ptr [[THERHS]], align 4
; MASKED-NEXT:    [[CMP415:%.*]] = icmp eq i32 [[TMP0]], [[TMP1]]
; MASKED-NEXT:    br i1 [[CMP415]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[WHILE_COND:.*]]:
; MASKED-NEXT:    [[INCDEC_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[THERHS_ADDR_016:%.*]], i64 4
; MASKED-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INCDEC_PTR:%.*]], align 4
; MASKED-NEXT:    [[TMP3:%.*]] = load i32, ptr [[INCDEC_PTR8]], align 4
; MASKED-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], [[TMP3]]
; MASKED-NEXT:    br i1 [[CMP4]], label %[[WHILE_BODY]], label %[[RETURN_LOOPEXIT:.*]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[THELHS_ADDR_017:%.*]] = phi ptr [ [[INCDEC_PTR]], %[[WHILE_COND]] ], [ [[THELHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[THERHS_ADDR_016]] = phi ptr [ [[INCDEC_PTR8]], %[[WHILE_COND]] ], [ [[THERHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[THELHS_ADDR_017]], i64 4
; MASKED-NEXT:    [[CMP5:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[ADD_PTR]]
; MASKED-NEXT:    br i1 [[CMP5]], label %[[RETURN_LOOPEXIT]], label %[[WHILE_COND]]
; MASKED:       [[RETURN_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[RETURN]]
; MASKED:       [[RETURN]]:
; MASKED-NEXT:    [[RETVAL_1:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[IF_ELSE]] ], [ false, %[[IF_ELSE3]] ], [ [[CMP5]], %[[RETURN_LOOPEXIT]] ]
; MASKED-NEXT:    ret i1 [[RETVAL_1]]
;
entry:
  %cmp.not = icmp eq i64 %theLHSLength, %theRHSLength
  br i1 %cmp.not, label %if.else, label %return

if.else:
  %cmp1 = icmp eq i64 %theLHSLength, 0
  br i1 %cmp1, label %return, label %if.else3

if.else3:
  %add.ptr = getelementptr inbounds nuw i32, ptr %theLHS, i64 %theLHSLength
  %0 = load i32, ptr %theLHS, align 4
  %1 = load i32, ptr %theRHS, align 4
  %cmp415 = icmp eq i32 %0, %1
  br i1 %cmp415, label %while.body, label %return

while.cond:
  %incdec.ptr8 = getelementptr inbounds nuw i8, ptr %theRHS.addr.016, i64 4
  %2 = load i32, ptr %incdec.ptr, align 4
  %3 = load i32, ptr %incdec.ptr8, align 4
  %cmp4 = icmp eq i32 %2, %3
  br i1 %cmp4, label %while.body, label %return

while.body:
  %theLHS.addr.017 = phi ptr [ %incdec.ptr, %while.cond ], [ %theLHS, %if.else3 ]
  %theRHS.addr.016 = phi ptr [ %incdec.ptr8, %while.cond ], [ %theRHS, %if.else3 ]
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %theLHS.addr.017, i64 4
  %cmp5 = icmp eq ptr %incdec.ptr, %add.ptr
  br i1 %cmp5, label %return, label %while.cond

return:
  %retval.1 = phi i1 [ false, %entry ], [ true, %if.else ], [ false, %if.else3 ], [ %cmp5, %while.body ], [ %cmp5, %while.cond ]
  ret i1 %retval.1
}
