; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=predicated -mattr=+v -S < %s | FileCheck %s
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=masked -mattr=+v -S < %s | FileCheck %s --check-prefix=MASKED
define dso_local noundef zeroext i1 @rawstrcmp_opt(ptr noundef readonly captures(address) %theLHS, ptr noundef readonly captures(none) %theRHS, ptr noundef readnone captures(address) %theEnd) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef zeroext i1 @rawstrcmp_opt(
; CHECK-SAME: ptr noundef readonly captures(address) [[THELHS:%.*]], ptr noundef readonly captures(none) [[THERHS:%.*]], ptr noundef readnone captures(address) [[THEEND:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[THELHS]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[THERHS]], align 1
; CHECK-NEXT:    [[CMP9:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP9]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN:.*]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_COND:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[THELHS]], i64 [[INDEX:%.*]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1, i32 16, i1 true)
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr [[TMP2]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr [[TMP5]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP4]], <vscale x 16 x i8> [[TMP6]], metadata !"ne", <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP4]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i1> @llvm.vp.or.nxv16i1(<vscale x 16 x i1> [[TMP7]], <vscale x 16 x i1> [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP9]], i1 false, <vscale x 16 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP3]] to i64
; CHECK-NEXT:    [[TMP12:%.*]] = add nuw nsw i64 [[INDEX]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i32 [[TMP10]], [[TMP3]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[THELHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP14]], align 1
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP16]], align 1
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i8 [[TMP15]], [[TMP17]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[WHILE_BODY]], label %[[RETURN_LOOPEXIT:.*]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX]] = phi i64 [ 0, %[[WHILE_BODY_PREHEADER]] ], [ [[TMP12]], %[[WHILE_COND]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[THELHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr i8, ptr [[THERHS]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[TMP21]], align 1
; CHECK-NEXT:    [[TMP23:%.*]] = or i8 [[TMP20]], [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp eq i8 [[TMP23]], 0
; CHECK-NEXT:    br i1 [[TMP24]], label %[[RETURN_LOOPEXIT]], label %[[WHILE_COND]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    [[INDEX2:%.*]] = phi i1 [ true, %[[WHILE_BODY]] ], [ [[TMP18]], %[[WHILE_COND]] ]
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[CMP_LCSSA:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[INDEX2]], %[[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[CMP_LCSSA]]
;
; MASKED-LABEL: define dso_local noundef zeroext i1 @rawstrcmp_opt(
; MASKED-SAME: ptr noundef readonly captures(address) [[THELHS:%.*]], ptr noundef readonly captures(none) [[THERHS:%.*]], ptr noundef readnone captures(address) [[THEEND:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; MASKED-NEXT:  [[ENTRY:.*]]:
; MASKED-NEXT:    [[TMP0:%.*]] = load i8, ptr [[THELHS]], align 1
; MASKED-NEXT:    [[TMP1:%.*]] = load i8, ptr [[THERHS]], align 1
; MASKED-NEXT:    [[CMP9:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; MASKED-NEXT:    br i1 [[CMP9]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[RETURN:.*]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[WHILE_COND:.*]]:
; MASKED-NEXT:    [[INCDEC_PTR5:%.*]] = getelementptr inbounds nuw i8, ptr [[THERHS_ADDR_011:%.*]], i64 1
; MASKED-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR:%.*]], align 1
; MASKED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[INCDEC_PTR5]], align 1
; MASKED-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP2]], [[TMP3]]
; MASKED-NEXT:    br i1 [[CMP]], label %[[WHILE_BODY]], label %[[RETURN_LOOPEXIT:.*]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[THERHS_ADDR_011]] = phi ptr [ [[INCDEC_PTR5]], %[[WHILE_COND]] ], [ [[THERHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[THELHS_ADDR_010:%.*]] = phi ptr [ [[INCDEC_PTR]], %[[WHILE_COND]] ], [ [[THELHS]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[THELHS_ADDR_010]], i64 1
; MASKED-NEXT:    [[CMP3:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[THEEND]]
; MASKED-NEXT:    br i1 [[CMP3]], label %[[RETURN_LOOPEXIT]], label %[[WHILE_COND]]
; MASKED:       [[RETURN_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[RETURN]]
; MASKED:       [[RETURN]]:
; MASKED-NEXT:    [[CMP_LCSSA:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[CMP3]], %[[RETURN_LOOPEXIT]] ]
; MASKED-NEXT:    ret i1 [[CMP_LCSSA]]
;
entry:
  %0 = load i8, ptr %theLHS, align 1
  %1 = load i8, ptr %theRHS, align 1
  %cmp9 = icmp eq i8 %0, %1
  br i1 %cmp9, label %while.body, label %return

while.cond:                                       ; preds = %while.body
  %incdec.ptr5 = getelementptr inbounds nuw i8, ptr %theRHS.addr.011, i64 1
  %2 = load i8, ptr %incdec.ptr, align 1
  %3 = load i8, ptr %incdec.ptr5, align 1
  %cmp = icmp eq i8 %2, %3
  br i1 %cmp, label %while.body, label %return

while.body:                                       ; preds = %entry, %while.cond
  %theRHS.addr.011 = phi ptr [ %incdec.ptr5, %while.cond ], [ %theRHS, %entry ]
  %theLHS.addr.010 = phi ptr [ %incdec.ptr, %while.cond ], [ %theLHS, %entry ]
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %theLHS.addr.010, i64 1
  %cmp3 = icmp eq ptr %incdec.ptr, %theEnd
  br i1 %cmp3, label %return, label %while.cond

return:                                           ; preds = %while.body, %while.cond, %entry
  %cmp.lcssa = phi i1 [ false, %entry ], [ %cmp3, %while.cond ], [ %cmp3, %while.body ]
  ret i1 %cmp.lcssa
}

define dso_local void @check_equality_crash(ptr noundef readonly captures(none) %N, ptr noundef captures(none) %C, ptr noundef readonly captures(none) %A, ptr noundef readonly captures(none) %B) local_unnamed_addr #1 {
; CHECK-LABEL: define dso_local void @check_equality_crash(
; CHECK-SAME: ptr noundef readonly captures(none) [[N:%.*]], ptr noundef captures(none) [[C:%.*]], ptr noundef readonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[N]], align 4
; CHECK-NEXT:    [[CMP12:%.*]] = icmp eq i32 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[CMP12]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[WHILE_END:.*]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = load i32, ptr [[C]], align 4
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ADD:%.*]], %[[IF_END:.*]] ], [ [[DOTPRE]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[N_ADDR_013:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], %[[IF_END]] ], [ [[N]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %[[WHILE_END_LOOPEXIT:.*]], label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    store i32 [[ADD]], ptr [[C]], align 4
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[N_ADDR_013]], i64 -4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[WHILE_BODY]], label %[[WHILE_END_LOOPEXIT]]
; CHECK:       [[WHILE_END_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[WHILE_END]]
; CHECK:       [[WHILE_END]]:
; CHECK-NEXT:    ret void
;
; MASKED-LABEL: define dso_local void @check_equality_crash(
; MASKED-SAME: ptr noundef readonly captures(none) [[N:%.*]], ptr noundef captures(none) [[C:%.*]], ptr noundef readonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
; MASKED-NEXT:  [[ENTRY:.*:]]
; MASKED-NEXT:    [[TMP0:%.*]] = load i32, ptr [[N]], align 4
; MASKED-NEXT:    [[CMP12:%.*]] = icmp eq i32 [[TMP0]], 0
; MASKED-NEXT:    br i1 [[CMP12]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[WHILE_END:.*]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    [[DOTPRE:%.*]] = load i32, ptr [[C]], align 4
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ADD:%.*]], %[[IF_END:.*]] ], [ [[DOTPRE]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[N_ADDR_013:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], %[[IF_END]] ], [ [[N]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 0
; MASKED-NEXT:    br i1 [[CMP1]], label %[[WHILE_END_LOOPEXIT:.*]], label %[[IF_END]]
; MASKED:       [[IF_END]]:
; MASKED-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A]], align 4
; MASKED-NEXT:    [[TMP3:%.*]] = load i32, ptr [[B]], align 4
; MASKED-NEXT:    [[ADD]] = add nsw i32 [[TMP3]], [[TMP2]]
; MASKED-NEXT:    store i32 [[ADD]], ptr [[C]], align 4
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[N_ADDR_013]], i64 -4
; MASKED-NEXT:    [[TMP4:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; MASKED-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP4]], 0
; MASKED-NEXT:    br i1 [[CMP]], label %[[WHILE_BODY]], label %[[WHILE_END_LOOPEXIT]]
; MASKED:       [[WHILE_END_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[WHILE_END]]
; MASKED:       [[WHILE_END]]:
; MASKED-NEXT:    ret void
;
entry:
  %0 = load i32, ptr %N, align 4
  %cmp12 = icmp eq i32 %0, 0
  br i1 %cmp12, label %while.body.preheader, label %while.end

while.body.preheader:                             ; preds = %entry
  %.pre = load i32, ptr %C, align 4
  br label %while.body

while.body:                                       ; preds = %while.body.preheader, %if.end
  %1 = phi i32 [ %add, %if.end ], [ %.pre, %while.body.preheader ]
  %N.addr.013 = phi ptr [ %incdec.ptr, %if.end ], [ %N, %while.body.preheader ]
  %cmp1 = icmp eq i32 %1, 0
  br i1 %cmp1, label %while.end, label %if.end

if.end:                                           ; preds = %while.body
  %2 = load i32, ptr %A, align 4
  %3 = load i32, ptr %B, align 4
  %add = add nsw i32 %3, %2
  store i32 %add, ptr %C, align 4
  %incdec.ptr = getelementptr inbounds i8, ptr %N.addr.013, i64 -4
  %4 = load i32, ptr %incdec.ptr, align 4
  %cmp = icmp eq i32 %4, 0
  br i1 %cmp, label %while.body, label %while.end

while.end:                                        ; preds = %if.end, %while.body, %entry
  ret void
}
