; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=predicated -mattr=+v -S < %s | FileCheck %s
; RUN: opt -passes='loop(loop-idiom-vectorize),instcombine' -mtriple=riscv64-unknown-linux-gnu -loop-idiom-vectorize-style=masked -mattr=+v -S < %s | FileCheck %s --check-prefix=MASKED

; typedef unsigned short XMLCh;
; bool equals(const XMLCh *const str1, const XMLCh *const str2) {
;   const XMLCh *psz1 = str1;
;   const XMLCh *psz2 = str2;
;   if (psz1 == 0 || psz2 == 0) {
;     if ((psz1 != 0 && *psz1) || (psz2 != 0 && *psz2))
;       return false;
;     else
;       return true;
;   }
;   while (*psz1 == *psz2) {
;     if (!*psz1)
;       return true;
;     psz1++;
;     psz2++;
;   }
;   return false;
; }
define dso_local noundef zeroext i1 @_Z6equalsPKtS0_(ptr noundef readonly captures(address_is_null) %str1, ptr noundef readonly captures(address_is_null) %str2) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef zeroext i1 @_Z6equalsPKtS0_(
; CHECK-SAME: ptr noundef readonly captures(address_is_null) [[STR1:%.*]], ptr noundef readonly captures(address_is_null) [[STR2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[STR1]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[STR2]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[IF_THEN:.*]], label %[[WHILE_COND_PREHEADER:.*]]
; CHECK:       [[WHILE_COND_PREHEADER]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[STR1]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[STR2]], align 2
; CHECK-NEXT:    [[CMP924:%.*]] = icmp eq i16 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP924]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[CLEANUP:.*]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOR_LHS_FALSE3:.*]], label %[[LAND_LHS_TRUE:.*]]
; CHECK:       [[LAND_LHS_TRUE]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[STR1]], align 2
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i16 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label %[[LOR_LHS_FALSE3]], label %[[CLEANUP]]
; CHECK:       [[LOR_LHS_FALSE3]]:
; CHECK-NEXT:    br i1 [[CMP1]], label %[[IF_ELSE:.*]], label %[[LAND_LHS_TRUE5:.*]]
; CHECK:       [[LAND_LHS_TRUE5]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[STR2]], align 2
; CHECK-NEXT:    [[TOBOOL6_NOT:%.*]] = icmp eq i16 [[TMP3]], 0
; CHECK-NEXT:    br i1 [[TOBOOL6_NOT]], label %[[IF_ELSE]], label %[[CLEANUP]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[TMP29:%.*]], %[[IF_END12:.*]] ], [ 0, %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i16, ptr [[STR1]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i16, ptr [[STR2]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    [[TMP8:%.*]] = or i16 [[TMP5]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i16 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[TMP9]], label %[[CLEANUP_LOOPEXIT:.*]], label %[[IF_END12]]
; CHECK:       [[IF_END12]]:
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i16, ptr [[STR1]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP11:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP12:%.*]] = shl nuw nsw i64 [[TMP11]], 4
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP12]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP14:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr [[TMP10]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP13]])
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[TMP14]], 0
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i16, ptr [[STR2]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP17:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr [[TMP16]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP13]])
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[TMP17]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[TMP14]], 1
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[TMP17]], 1
; CHECK-NEXT:    [[TMP21:%.*]] = call i32 @llvm.umin.i32(i32 [[TMP19]], i32 [[TMP20]])
; CHECK-NEXT:    [[TMP22:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP15]], <vscale x 16 x i16> [[TMP18]], metadata !"ne", <vscale x 16 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP23:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP22]], i1 false, <vscale x 16 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP24:%.*]] = icmp eq i32 [[TMP23]], [[TMP21]]
; CHECK-NEXT:    [[TMP25:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP15]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP26:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv16i1(<vscale x 16 x i1> [[TMP25]], i1 false, <vscale x 16 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP27:%.*]] = icmp eq i32 [[TMP26]], [[TMP21]]
; CHECK-NEXT:    [[DOTNOT4:%.*]] = and i1 [[TMP24]], [[TMP27]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[TMP23]], [[TMP26]]
; CHECK-NEXT:    [[TMP28:%.*]] = zext i32 [[TMP21]] to i64
; CHECK-NEXT:    [[TMP29]] = add nuw nsw i64 [[INDEX]], [[TMP28]]
; CHECK-NEXT:    br i1 [[DOTNOT4]], label %[[WHILE_BODY]], label %[[CLEANUP_LOOPEXIT]]
; CHECK:       [[CLEANUP_LOOPEXIT]]:
; CHECK-NEXT:    [[INDEX1:%.*]] = phi i1 [ true, %[[WHILE_BODY]] ], [ [[DOTNOT]], %[[IF_END12]] ]
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i1 [ true, %[[IF_ELSE]] ], [ false, %[[LAND_LHS_TRUE5]] ], [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[WHILE_COND_PREHEADER]] ], [ [[INDEX1]], %[[CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    ret i1 [[RETVAL_0]]
;
; MASKED-LABEL: define dso_local noundef zeroext i1 @_Z6equalsPKtS0_(
; MASKED-SAME: ptr noundef readonly captures(address_is_null) [[STR1:%.*]], ptr noundef readonly captures(address_is_null) [[STR2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; MASKED-NEXT:  [[ENTRY:.*:]]
; MASKED-NEXT:    [[CMP:%.*]] = icmp eq ptr [[STR1]], null
; MASKED-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[STR2]], null
; MASKED-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; MASKED-NEXT:    br i1 [[OR_COND]], label %[[IF_THEN:.*]], label %[[WHILE_COND_PREHEADER:.*]]
; MASKED:       [[WHILE_COND_PREHEADER]]:
; MASKED-NEXT:    [[TMP0:%.*]] = load i16, ptr [[STR1]], align 2
; MASKED-NEXT:    [[TMP1:%.*]] = load i16, ptr [[STR2]], align 2
; MASKED-NEXT:    [[CMP924:%.*]] = icmp eq i16 [[TMP0]], [[TMP1]]
; MASKED-NEXT:    br i1 [[CMP924]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[CLEANUP:.*]]
; MASKED:       [[WHILE_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[WHILE_BODY:.*]]
; MASKED:       [[IF_THEN]]:
; MASKED-NEXT:    br i1 [[CMP]], label %[[LOR_LHS_FALSE3:.*]], label %[[LAND_LHS_TRUE:.*]]
; MASKED:       [[LAND_LHS_TRUE]]:
; MASKED-NEXT:    [[TMP2:%.*]] = load i16, ptr [[STR1]], align 2
; MASKED-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i16 [[TMP2]], 0
; MASKED-NEXT:    br i1 [[TOBOOL_NOT]], label %[[LOR_LHS_FALSE3]], label %[[CLEANUP]]
; MASKED:       [[LOR_LHS_FALSE3]]:
; MASKED-NEXT:    br i1 [[CMP1]], label %[[IF_ELSE:.*]], label %[[LAND_LHS_TRUE5:.*]]
; MASKED:       [[LAND_LHS_TRUE5]]:
; MASKED-NEXT:    [[TMP3:%.*]] = load i16, ptr [[STR2]], align 2
; MASKED-NEXT:    [[TOBOOL6_NOT:%.*]] = icmp eq i16 [[TMP3]], 0
; MASKED-NEXT:    br i1 [[TOBOOL6_NOT]], label %[[IF_ELSE]], label %[[CLEANUP]]
; MASKED:       [[IF_ELSE]]:
; MASKED-NEXT:    br label %[[CLEANUP]]
; MASKED:       [[WHILE_BODY]]:
; MASKED-NEXT:    [[TMP4:%.*]] = phi i16 [ [[TMP5:%.*]], %[[IF_END12:.*]] ], [ [[TMP0]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[PSZ2_026:%.*]] = phi ptr [ [[INCDEC_PTR13:%.*]], %[[IF_END12]] ], [ [[STR2]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[PSZ1_025:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], %[[IF_END12]] ], [ [[STR1]], %[[WHILE_BODY_PREHEADER]] ]
; MASKED-NEXT:    [[TOBOOL10_NOT:%.*]] = icmp eq i16 [[TMP4]], 0
; MASKED-NEXT:    br i1 [[TOBOOL10_NOT]], label %[[CLEANUP_LOOPEXIT:.*]], label %[[IF_END12]]
; MASKED:       [[IF_END12]]:
; MASKED-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr [[PSZ1_025]], i64 2
; MASKED-NEXT:    [[INCDEC_PTR13]] = getelementptr inbounds nuw i8, ptr [[PSZ2_026]], i64 2
; MASKED-NEXT:    [[TMP5]] = load i16, ptr [[INCDEC_PTR]], align 2
; MASKED-NEXT:    [[TMP6:%.*]] = load i16, ptr [[INCDEC_PTR13]], align 2
; MASKED-NEXT:    [[CMP9:%.*]] = icmp eq i16 [[TMP5]], [[TMP6]]
; MASKED-NEXT:    br i1 [[CMP9]], label %[[WHILE_BODY]], label %[[CLEANUP_LOOPEXIT]]
; MASKED:       [[CLEANUP_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[CLEANUP]]
; MASKED:       [[CLEANUP]]:
; MASKED-NEXT:    [[RETVAL_0:%.*]] = phi i1 [ true, %[[IF_ELSE]] ], [ false, %[[LAND_LHS_TRUE5]] ], [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[WHILE_COND_PREHEADER]] ], [ [[TOBOOL10_NOT]], %[[CLEANUP_LOOPEXIT]] ]
; MASKED-NEXT:    ret i1 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %str1, null
  %cmp1 = icmp eq ptr %str2, null
  %or.cond = or i1 %cmp, %cmp1
  br i1 %or.cond, label %if.then, label %while.cond.preheader

while.cond.preheader:                             ; preds = %entry
  %0 = load i16, ptr %str1, align 2
  %1 = load i16, ptr %str2, align 2
  %cmp924 = icmp eq i16 %0, %1
  br i1 %cmp924, label %while.body, label %cleanup

if.then:                                          ; preds = %entry
  br i1 %cmp, label %lor.lhs.false3, label %land.lhs.true

land.lhs.true:                                    ; preds = %if.then
  %2 = load i16, ptr %str1, align 2
  %tobool.not = icmp eq i16 %2, 0
  br i1 %tobool.not, label %lor.lhs.false3, label %cleanup

lor.lhs.false3:                                   ; preds = %land.lhs.true, %if.then
  br i1 %cmp1, label %if.else, label %land.lhs.true5

land.lhs.true5:                                   ; preds = %lor.lhs.false3
  %3 = load i16, ptr %str2, align 2
  %tobool6.not = icmp eq i16 %3, 0
  br i1 %tobool6.not, label %if.else, label %cleanup

if.else:                                          ; preds = %land.lhs.true5, %lor.lhs.false3
  br label %cleanup

while.body:                                       ; preds = %while.cond.preheader, %if.end12
  %4 = phi i16 [ %5, %if.end12 ], [ %0, %while.cond.preheader ]
  %psz2.026 = phi ptr [ %incdec.ptr13, %if.end12 ], [ %str2, %while.cond.preheader ]
  %psz1.025 = phi ptr [ %incdec.ptr, %if.end12 ], [ %str1, %while.cond.preheader ]
  %tobool10.not = icmp eq i16 %4, 0
  br i1 %tobool10.not, label %cleanup, label %if.end12

if.end12:                                         ; preds = %while.body
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %psz1.025, i64 2
  %incdec.ptr13 = getelementptr inbounds nuw i8, ptr %psz2.026, i64 2
  %5 = load i16, ptr %incdec.ptr, align 2
  %6 = load i16, ptr %incdec.ptr13, align 2
  %cmp9 = icmp eq i16 %5, %6
  br i1 %cmp9, label %while.body, label %cleanup

cleanup:                                          ; preds = %while.body, %if.end12, %while.cond.preheader, %land.lhs.true, %land.lhs.true5, %if.else
  %retval.0 = phi i1 [ true, %if.else ], [ false, %land.lhs.true5 ], [ false, %land.lhs.true ], [ false, %while.cond.preheader ], [ %tobool10.not, %if.end12 ], [ %tobool10.not, %while.body ]
  ret i1 %retval.0
}
